### ISSUE TITLE
cant run on lubuntu

### ISSUE THREAD

**Issue by Pradhyu-18** [Jack477/CommanderPi#13]
tried to install on lubuntu but failed

**Comment by Jack477** [comment]
Show me error, you can't run ./install.sh or you can't run app?

**Comment by Blak-DK** [comment]
in ubuntu we get this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/Desktop/commanderpi.desktop'
chmod: cannot access '/home/pi/Desktop/commanderpi.desktop': No such file or directory

**Comment by Jack477** [comment]
My bad, I forgot to set all paths as relative. Fixed. You should remove all old files and install new.
Tell me if it works fine
https://drive.google.com/file/d/1x1ZTkqMQpGkp8CQa2MY4aljvmVIJFaRd/view?usp=sharing

**Comment by Pradhyu-18** [comment]
still not working

**Comment by Jack477** [comment]
What kind of error do you have?

**Comment by Pradhyu-18** [comment]
root/ path error..

**Comment by Jack477** [comment]
Do you use sudo to install? Don't use it. Type ./install.sh without sudo

**Comment by Pradhyu-18** [comment]
above method worked and created a desktop shortcut.........but it's not working (not opening the app)

**Comment by Jack477** [comment]
Type this and show me error `sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}`

**Comment by Pradhyu-18** [comment]
Exist and read
28.9
Total: 28.95
Used: 8.37
Free: 20.56
Traceback (most recent call last):
  File "/home/pradhyu/CommanderPi/src/main.py", line 9, in <module>
    import gui as g
  File "/home/pradhyu/CommanderPi/src/gui.py", line 4, in <module>
    import resources as rs
  File "/home/pradhyu/CommanderPi/src/resources.py", line 180, in <module>
    f = open(config_path)
FileNotFoundError: [Errno 2] No such file or directory: '/boot/config.txt'

**Comment by Jack477** [comment]
Are you using RaspberryPi 4 or 3? This app is designed for PI4 and it should works on 3b, it's not for desktop or others sbc.

**Comment by Pradhyu-18** [comment]
i am using raspberry pi 4

**Comment by Jack477** [comment]
Where is config.txt in lubuntu?

**Comment by Pradhyu-18** [comment]
in system-boot

**Comment by Jack477** [comment]
Give me a path and show file content

**Comment by Pradhyu-18** [comment]
![Screenshot at 2020-07-15 18-07-02](https://user-images.githubusercontent.com/66906596/87545820-3730f100-c6c6-11ea-8107-32edcec40d7e.png)

**Comment by Pradhyu-18** [comment]
![Annotation 2020-07-15 181546](https://user-images.githubusercontent.com/66906596/87546478-3fd5f700-c6c7-11ea-9fc8-34ea3ff911b8.jpg)

in ubuntu instead of setting overclock parameter in config.txt  user sets this parameter in usercfg.txt

**Comment by Pradhyu-18** [comment]
https://www.youtube.com/watch?v=SzofbSAU1j8

as described in this video on 5:00

**Comment by Blak-DK** [comment]
Fresh install  of ubuntu-mate-20.04-beta1-desktop-arm64+raspi 
Installing picommander with 
1.    chmod +x install.sh
2.    ./install.sh

error
  File "c_desktop.py", line 11, in <module>
    f = open(d_dir, "w+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/brian/Desktop/commanderpi.desktop'
chmod: cannot access '/home/brian/Desktop/commanderpi.desktop': No such file or directory

No desktop shortcut.

**Comment by Pradhyu-18** [comment]
> Fresh install of ubuntu-mate-20.04-beta1-desktop-arm64+raspi
> Installing picommander with
> 
> 1. chmod +x install.sh
> 2. ./install.sh
> 
> error
> File "c_desktop.py", line 11, in
> f = open(d_dir, "w+")
> FileNotFoundError: [Errno 2] No such file or directory: '/home/brian/Desktop/commanderpi.desktop'
> chmod: cannot access '/home/brian/Desktop/commanderpi.desktop': No such file or directory
> 
> No desktop shortcut.

Extract commanderpi in /home/brian in stead of desktop....
And run Sudo chmod +x install.sh in commanderpi folder
Also ./install.sh without sudo

**Comment by Jack477** [comment]
It's strange, try this: https://drive.google.com/file/d/1qIAX5WBxxerupzHz1RtS-IAjJZ3Qofn6/view?usp=sharing
I will install ubuntu on Pi today and I will do some changes for compatibility

**Comment by Pradhyu-18** [comment]
hey it worked by typing this command you gave sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}.......
but not run by the desktop app shortcut that install.sh creates

**Comment by Jack477** [comment]
Hmm delete app shortcut manually and try again `./install .sh` </br>Desktop shortcut should run start.sh file which use `sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}`. </br>If it doesn't work too, try go to CommanderPi/src and type `./start.sh`

**Comment by Pradhyu-18** [comment]
i edited the commanderpi.desktop shortcut......
edited Terminal=true....every time you need to enter password to run it...
chmod not working because of ./install.sh has no privileges

**Comment by Jack477** [comment]
Oh it's matter of ubuntu, beacuse you need to enter password to run sudo, in raspbian you don't
https://phpraxis.wordpress.com/2016/09/27/enable-sudo-without-password-in-ubuntudebian/

**Comment by Pradhyu-18** [comment]
now working perfectly......can you change the bootloader path for ubuntu?

**Comment by Jack477** [comment]
I will install ubuntu on my pi and try to make it compatible

**Comment by wjgeorge** [comment]
this will certainly not run on Ubuntu as configured. It depends on vcgencmd, not part of the Ubuntu distribution.

the code doesnt check if the command isnt found:

 CommanderPi/src/start.sh 
Traceback (most recent call last):
  File "/home/ubuntu/CommanderPi/src/main.py", line 22, in <module>
    main()
  File "/home/ubuntu/CommanderPi/src/main.py", line 18, in main
    start = g.Window()
  File "/home/ubuntu/CommanderPi/src/gui.py", line 671, in __init__
    refresh()
  File "/home/ubuntu/CommanderPi/src/gui.py", line 661, in refresh
    ptext = rs.refusage()
  File "/home/ubuntu/CommanderPi/src/resources.py", line 130, in refusage
    buff=int(buff)
ValueError: invalid literal for int() with base 10: 'gen'

**Comment by Jack477** [comment]
Added path for Ubuntu config.txt

**Comment by paulwratt** [comment]
@wjgeorge `vcgencmd` should still be included, because its the Raspberry Pi version (just like they have to include the other RPi specific libraries normally found in `/opt/vc`)

**Comment by paulwratt** [comment]
`vcgencmd` _is_ included with Ubuntu 20.10 on RPi4 (I saw someone type the command on a YT review)

**Comment by Jack477** [comment]
Oh so it is included in 20.10<=version yes? Could you test is it works then?
