### ISSUE TITLE
IP addresses are truncated by 1 digit

### ISSUE THREAD

**Issue by sgbeal** [Jack477/CommanderPi#15]
Minor cosmetic issue: on TwisterOS, at least, the IP addresses, both v4 and v6, are truncated by 1 digit in the network view. Here's a comparison on CommanderPi and ifconfig:

![Screenshot_2020-08-07_16-44-55](https://user-images.githubusercontent.com/235303/89690936-5b4eaf00-d8cd-11ea-8554-8e5f1133c3d3.png)

Note that both IPs are truncated but the MAC is not.

**Comment by Jack477** [comment]
Fixed.
