### ISSUE TITLE
wrong instructions in readme.txt

### ISSUE THREAD

**Issue by paulwratt** [Jack477/CommanderPi#17]
in `readme.txt`:
>  Run sudo ./install.sh

should be:
>  Run ./install.sh

according to `README.md`

also note that is the old way to install, and should "fail gracefully" or (better) adapt

**Comment by Jack477** [comment]
What do you mean _should "fail gracefully" or (better) adapt_?

**Comment by paulwratt** [comment]
the documented install procedure should adapt. I know you have changed the installer so it can be done without sudo/root, so maybe its a moot point.

I have to wait to get back to this, but as long as the text in the README.md is correct, that will be fine
