### ISSUE TITLE
Error message on Raspbian

### ISSUE THREAD

**Issue by Mikez333** [Jack477/CommanderPi#2]
I installed the program on raspbian, and when I ran the program or ran test.desktop, I got the error message : Invalid desktop entry file: '/home/pi/Desktop/test.desktop'

**Comment by Jack477** [comment]
Do you install it with sudo?

**Comment by Jack477** [comment]
Download new version and try

**Comment by Mikez333** [comment]
still says Invalid desktop entry file: '/home/pi/Desktop/test.desktop'. I am running RPI3, but when i use commander pi on twister os it worked fine (aside from the overclock making a blank screen during boot)

**Comment by Jack477** [comment]
Show me your path to CommanderPi and try run by sudo ./start.sh in src folder

**Comment by Mikez333** [comment]
i got python3: can't open file '/home/pi/CommanderPi/src/main.py': [Errno 2] No such file or directory
and the path is /home/pi/Desktop/CommanderPi

**Comment by Mikez333** [comment]
I think I fixed it! I watched ETA prime's tutorial and I didn't move the commander pi folder to my pi user folder. That should be changed sometime in the future. thanks for your help!
