### ISSUE TITLE
Paths should be changed to CommanderPi

### ISSUE THREAD

**Issue by Botspot** [Jack477/CommanderPi#3]
I cloned this repo with this command:

    git clone https://github.com/Jack477/CommanderPi

It cloned to `/home/pi/CommanderPi`.
For some reason, all the scripts and the .desktop file expects the cloned directory to be Commander_Pi. (<-- with an underscore, "_")
Therefore all the scripts are broken.

**Comment by Jack477** [comment]
Yep, my bad thanks for fix issue.

**Comment by Botspot** [comment]
No prob. Issue #2 was also related, so you can close that one too.
