### ISSUE TITLE
change start.sh to use SH instead of BASH

### ISSUE THREAD

**Issue by paulwratt** [Jack477/CommanderPi#32]
(I have other PR's and since this is a one liner ..)
The shell startup line in `~/CommanderPi/src/start.sh` should be change from:
```
#!/bin/bash
sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}> log.txt

```
to:
```
#!/bin/sh
sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}> log.txt

```
This way it will work on any setup, not just ones that have `bash` installed.

**NOTE:** the same should be done with `~/CommanderPi/install.sh`too, as there is nothing BASH specific in that file either. SH is always preferable of BASH for scripts, unless there an explicit need for BASH specific command usage (which there are always known workarounds for anyway)

**Comment by Jack477** [comment]
Alright, pushed.
