### ISSUE TITLE
Commander Pi not running or Opening at all?

### ISSUE THREAD

**Issue by TyronDawson** [Jack477/CommanderPi#34]
Followed full tutorial on ETA primes youtube channel. Have the Commander Pi app on my desktop now. When I click on it and say execute in terminal the hourglass appears on my cursor and then nothing happens at all?

Tried whole process again and same issue. I am running a Pi 4 booting from and SSD

**Comment by Rasberry-Pi-Reviews** [comment]
I also had the same problem, I want to overclock my Rasberry Pi 4 but I dont want to go through the long process.

**Comment by Jack477** [comment]
Did you installed at /home/pi/CommanderPi and installed by `. /install.sh` without sudo?

**Comment by TyronDawson** [comment]
Thanks I just installed TwisterOS and it's working perfect now!!
