### ISSUE TITLE
No able to run on raspberry pi OS 64 bit

### ISSUE THREAD

**Issue by cheehoong** [Jack477/CommanderPi#36]
Python 3.7.3 (/usr/bin/python3)
>>> %cd /tmp/xa-9B31T0
>>> %Run c_desktop.py
Traceback (most recent call last):
  File "/tmp/xa-9B31T0/c_desktop.py", line 7, in <module>
    user = sys.argv[1]
IndexError: list index out of range
>>>

**Comment by Jack477** [comment]
Do you see it when you install it?

**Comment by cheehoong** [comment]
After install, not ablt to run it via the menu icon/button. Desktop icon also won't run.
I run it on thonny, and it show me this.

**Comment by cheehoong** [comment]
sorry, i found the problem. My bad.
I put it in /home/pi/Downloads/CommanderPi folder.
after i move it to /home/pi/CommanderPi....  it run
