### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by memidhun** [Jack477/CommanderPi#40]
I am using kali linux in rasberry pi 4 model B . I downloaded commander pi unzip it in home directory and all the logos shown up but it was not starting so i thought the commanderpi folder should be in the root directory.. i don't know how to uninstall so i just deleted the folder and created a new one in root directory, and once again i did ./install.sh and i got the same problem .
![Screenshot_2020-12-14_13-29-01](https://user-images.githubusercontent.com/67965127/102086679-5caa5e00-3e10-11eb-96e9-92a2d9ebcd87.png)

also can anyone tell me how to completely uninstall this CommanderPi?

**Comment by Jack477** [comment]
To uninstall just delete folder with files. Don't install it as root user.

**Comment by memidhun** [comment]
> To uninstall just delete folder with files. Don't install it as root user.

Still it's not runnung..I tried clicking the desktop icon

**Comment by Jack477** [comment]
Type this in terminal and tell me what you see `sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}`

**Comment by memidhun** [comment]
> sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME}

Traceback (most recent call last):
  File "/home/kali/CommanderPi/src/main.py", line 9, in <module>
    import gui as g
  File "/home/kali/CommanderPi/src/gui.py", line 4, in <module>
    import resources as rs
  File "/home/kali/CommanderPi/src/resources.py", line 16, in <module>
    home_path = sys.argv[1]
NameError: name 'sys' is not defined

**Comment by Jack477** [comment]
Try this version, I've added manually sys import
[CommanderPi.zip](https://github.com/Jack477/CommanderPi/files/5695614/CommanderPi.zip)

**Comment by memidhun** [comment]
> Try this version, I've added manually sys import
> [CommanderPi.zip](https://github.com/Jack477/CommanderPi/files/5695614/CommanderPi.zip)

Traceback (most recent call last):
  File "/home/kali/CommanderPi/src/main.py", line 9, in <module>
    import gui as g
  File "/home/kali/CommanderPi/src/gui.py", line 4, in <module>
    import resources as rs
  File "/home/kali/CommanderPi/src/resources.py", line 188, in <module>
    print(refusage())
  File "/home/kali/CommanderPi/src/resources.py", line 165, in refusage
    buff=int(buff)
ValueError: invalid literal for int() with base 10: 'gen'

**Comment by Jack477** [comment]
Try this, if it wont work type this in terminal and show me your output `vcgencmd measure_clock v3d` I guess problem depends on Kali beacuse CommanderPi is designed for Debian/Raspbian.
[CommanderPi.zip](https://github.com/Jack477/CommanderPi/files/5697723/CommanderPi.zip)
