### ISSUE TITLE
CommanderPi can not run for Raspberry Ubuntu20.1

### ISSUE THREAD

**Issue by xiangdongping999** [Jack477/CommanderPi#46]
Hello sir:

I download the install zip,and installed app.
but i run this app ,this app is no reaction.
use the terminal run the start.sh not run and show some error information (pic 1)
![pic1](https://user-images.githubusercontent.com/62729544/105565842-d0bb1880-5d63-11eb-8514-0d9e79d89fa4.png)
I read some issues
used sudo python3 ${HOME}/CommanderPi/src/main.py ${HOME} ,(pic2)
![pic2](https://user-images.githubusercontent.com/62729544/105565965-81291c80-5d64-11eb-86c0-5a9ac4d49843.png)
and i surety installed psutil (pic3)
![pic3](https://user-images.githubusercontent.com/62729544/105566054-07456300-5d65-11eb-8eb5-eaa15273544b.png)
How to fix ,Please help me! 
Thank you!

PS:I am from china, english is not good.

**Comment by Jack477** [comment]
Hi, try with `pip3 install psutil`, also check is CommanderPi installed in your home directory as ` /home/<username>/CommanderPi ` NO AS `/root`!

**Comment by xiangdongping999** [comment]
hello sir

I try with pip3 install psutil (pip3 install)
![pip3 install](https://user-images.githubusercontent.com/62729544/105577736-5d8ec200-5db6-11eb-8d44-239cadb2aa6b.png)
and check the file (file)
![file](https://user-images.githubusercontent.com/62729544/105577756-77c8a000-5db6-11eb-948b-13981de45d44.png)
everything is ok but app not run.

thank you !

**Comment by Jack477** [comment]
Hmm, try install psutil with sudo, I mean `sudo pip3 install psutil`

**Comment by xiangdongping999** [comment]
hello sir:
I try install psutil with sudo , but app not run.
![sudo pip3](https://user-images.githubusercontent.com/62729544/105618515-04a94300-5e23-11eb-8f0d-7a5103eecae1.png)

and i in terminal run the start.sh $ python main.py 
this time show the error information are different (resources.py)
![start-sh](https://user-images.githubusercontent.com/62729544/105618520-1ab70380-5e23-11eb-8c7f-fd0457587e9b.png)
![main-py](https://user-images.githubusercontent.com/62729544/105618521-20144e00-5e23-11eb-91a0-484a396b3091.png)
run start,sh error line before is line6, now is line248
run main.py error line before is line6, now is line17

I need edit resoures.py ? if need edit ,how to edit ? 

Thank you!

**Comment by xiangdongping999** [comment]
hello sir:

Do you have any way for fix this ?

**Comment by Jack477** [comment]
Hello, what is path for your config.txt file?

**Comment by Itai-Nelken** [comment]
I think its `boot/firmware/config.txt` in Ubuntu, but the file where you should change things has a different name.

**Comment by Jack477** [comment]
Replace `resources.py` with this file https://drive.google.com/file/d/10D0gSCooz9w-sQ7wxkzowJM7WV-eqMWw/view?usp=sharing

**Comment by xiangdongping999** [comment]
hello sir
I try this way ,but app is not run.
I download this file and changed.
I Added the config file path (pic:config)
![加入config](https://user-images.githubusercontent.com/62729544/106892391-f7dff580-6726-11eb-82fc-cd84e00ba90c.png)
This way is right ?
And test start.sh
![start](https://user-images.githubusercontent.com/62729544/106892476-1645f100-6727-11eb-8159-581530f42399.png)
And test main.py
![main](https://user-images.githubusercontent.com/62729544/106892534-2a89ee00-6727-11eb-8585-fdada434cdfd.png)

What's wrong with me ?

**Comment by Jack477** [comment]
Im sorry my bad, I sent you not realesed version of CommanderPi. This file should be fine for you https://drive.google.com/file/d/1oeypiH-ju3lQw0Y_3Z6nCoaoCZFIF6Og/view?usp=sharing

**Comment by xiangdongping999** [comment]
Hello sir
Thank you very much!
run the start.sh ,software is running.
menu desktop not work
but this software can running is well

thank you~
