### ISSUE TITLE
Can you help, trying to install Commander Pi on RaspPi4b 8GB running Windows10, downloaded sip file but cant seem to run?

### ISSUE THREAD

**Issue by Laurenceellis** [Jack477/CommanderPi#47]

**Comment by Laurenceellis** [comment]
![image](https://user-images.githubusercontent.com/60437092/105616113-54105480-5dcc-11eb-893d-070c6473e493.png)

**Comment by Laurenceellis** [comment]
anything I type after this - says it does not recognise as an operable file

**Comment by KinoZampie** [comment]
Sorry but CommanderPi is designed to run on Linux operating systems, specifically Raspberry Pi OS or TwisterOS. You will not be able to run CommanderPi on Windows 10

**Comment by Laurenceellis** [comment]
Arrgg OK was hoping to overclock etc. through this - will have to go back through the long route

**Comment by Itai-Nelken** [comment]
> Arrgg OK was hoping to overclock etc. through this - will have to go back through the long route

@Laurenceellis use WoRCP for that, you can get it from the WoR discord server.

**Comment by Jack477** [comment]
Hi like @KinoZampie said CommanderPi is designed for Linux. I don't think it would be port to WoR anytime soon
