### ISSUE TITLE
Reccomended values WAY TOO HIGH

### ISSUE THREAD

**Issue by Mikez333** [Jack477/CommanderPi#6]
Tried recommended values and my pi turned into 
![image](https://user-images.githubusercontent.com/44128563/83579462-919b3700-a4f6-11ea-891a-e838d14f338c.png)

**Comment by Raymond-Ursher** [comment]
The recommended values are NOT too high...you must have a different issue because I've been over-clocked at 2000mhz on CPU and 600mhz on GPU for a month straight... it's stable.

**Comment by Raymond-Ursher** [comment]
Do you have an aftermarket CPU cooler?

**Comment by dikodahan** [comment]
I agree. Recommended values are just fine.
You need quality active cooling for the high values to work though.

**Comment by Mikez333** [comment]
I have a fan and heatsink. I am using an RPI 3 though.

**Comment by dikodahan** [comment]
That's your issue then!
the listed recommended numbers are for RPi4. look up online for the recommended numbers for your Pi model.
@Jack477 has an enhancement request to recognize your Pi model and add recommended ones accordingly.

**Comment by Mikez333** [comment]
https://pimylifeup.com/raspberry-pi-overclock/ for overclock info for pi versions excluding 4

**Comment by Jack477** [comment]
This app is designed for Raspberry Pi **4** ! I will add in future Pi 3 support but now all of thing are made for Pi 4! It could works on Pi 3 sure, but it's made for Pi 4. I will add auto detect which Raspberry user have and then it will be showing proposed values for each Pi model.
