### ISSUE TITLE
Doesn’t Work on Pi 4

### ISSUE THREAD

**Issue by prashantdwivedi** [Jack477/CommanderPi#61]
Try to open it not open

**Comment by Jack477** [comment]
Could you explain what "not open"?

**Comment by MagicAndre1981** [comment]
https://github.com/Jack477/CommanderPi/issues/54

**Comment by Jack477** [comment]
What is path to your installed Comannder Pi, what OS do you use and do you have the newest version?

**Comment by MagicAndre1981** [comment]
I'm using the normal RaspiOS on Pi4 and the app doesn't start when not in expected folder. I was also using desktop first. Now it works, this was just a hint for @prashantdwivedi .

There is also a ; missing in [install command](https://github.com/Jack477/CommanderPi#to-download-the-software)

**Comment by prashantdwivedi** [comment]
Typical method installation does not work. I find it extracted on root and install then perform—that method I see on youtube.
Otherside try to install from the download folder; it did not work app.

**Comment by Jack477** [comment]
@MagicAndre1981 I have added missing `;` @prashantdwivedi  now it should works fine

**Comment by prashantdwivedi** [comment]
Cool, I will check it later. Thanks for the fix.
