### ISSUE TITLE
Commander Pi won't start when using xrdp to remote in to Pi

### ISSUE THREAD

**Issue by nikescar1** [Jack477/CommanderPi#7]
```
pi@raspberrypi:~/CommanderPi/src $ sudo python3 /home/pi/CommanderPi/src/main.py > a.txt
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/home/pi/CommanderPi/src/main.py", line 22, in <module>
    main()
  File "/home/pi/CommanderPi/src/main.py", line 18, in main
    start = g.Window()
  File "/home/pi/CommanderPi/src/gui.py", line 193, in __init__
    master = tk.Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":10.0"
```
When remoting in and trying to run the program I get the above error. I solved it using [THIS](https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=26934&p=242112&hilit=tkinter+display#p243068) post.

Run `sudo cp ~pi/.Xauthority ~root/` in the terminal. Then CommanderPi starts as expected.

**Comment by Jack477** [comment]
Hmm, try with new version of CommanderPi

**Comment by nikescar1** [comment]
It's not a problem with your program, it has to do with tkinter not finding the display because of some sort of X11 display permissions.

**Comment by Jack477** [comment]
Ok so I close issue

**Comment by ChaosBlades** [comment]
Seems you have to run that command on every reboot. Very annoying.
