### ISSUE TITLE
Unable to start program 

### ISSUE THREAD

**Issue by Narbife** [Jack477/CommanderPi#8]
Hello!
I'm unable to start your program after installing it. If I try to run it from the desktop nothing happens, and if I try to run it from the terminal sudo ./start.sh, the following error message appears: "ModuleNotFoundError: no module named 'psutil'.

Thank you in advance for your time.

**Comment by Narbife** [comment]
Here's a picture of the error.
![IMG_20200612_152450](https://user-images.githubusercontent.com/66833202/84507384-058cca80-acc1-11ea-8343-ee927929ac4e.jpg)

**Comment by Jack477** [comment]
Try this command `sudo pip install --upgrade psutil`

**Comment by prezftb09** [comment]
I am having the same issue and I tried the above command to no avail.

**Comment by Narbife** [comment]
I tried that as well, but it unfortunately did not fix my issue. What eventually did was following the video bellow. After fully updating everything with the commands he showed and rebooting the system, I was able to use the software. 

https://youtu.be/RBpAkTvBbYg

The last two probably fixed the issue.
